# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176bcd42cc5198784c43af50b8720b2cbc7b7b6f96aa6a265ed9eb1fbe31eca9174b55cefcc868237744fc5e748768a78c15f0dd22c73f2d96473f5360ce722a

test:
  secret_key_base: 31f07c39d80a9ff630e6676dccc39ba15cd39377a6017119c2d608b5bc8967e7829f48bdf2a167de7eabff521624374cc7b24ff2f899dd1b7a83f442bc4043a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
